@startuml

' 囲碁というゲームについて
object ルール

object ターン制 {
  交互に一手ずつ石を置く
  石は黒と白
  黒が先行する
}
object 置き碁 {
  所謂ハンデ戦
  盤面の星(黒い点)に
  黒石を置いた状態でスタート
  この場合は白が先行
}
object 終局 {
  ゲームの終了
  双方がパスしたら終わり
}

object 地 {
  自分の石で囲んだ陣地
}
object 着手禁止点 {
  石を置けない場所
  基本的には相手の地
  アタリになる場合は例外
}
object アタリ {
  後一手で相手の石をとれる状態
}

ルール o-l- ターン制
ルール o-u- 地
ルール o-d- 着手禁止点
ルール o- アタリ
着手禁止点 <-d- アタリ : 例外
ターン制 <|-- 置き碁
ターン制 <|-- 終局

' 対局に勝つための知識
object 局面

object コウ {

}

局面 <|-- コウ

object 戦略
object 戦術

object コスミ {
  斜めに行くこと？
}

戦術 <|-- コスミ

' 練習方法
object 練習方法

object 詰め碁
object 棋譜並べ {
  既存の対局を棋譜の順序に従って再現する
}

練習方法 <|-- 詰め碁 : 死活の練習
練習方法 <|-- 棋譜並べ : 序盤の練習

' 関わる人について
object 棋士

' まだ分類できないもの
object 心得 {
  東大教養囲碁講座から
}
object まわりにきたらご挨拶
object ナナメにご用心
object 入れてください入れません
object 自分の用心
object 自分の弱い石から動くことを検討する
object キリチガイは場合によって対応を変える
object 離してきたら離して打つ
object むやみにツケない

心得 o-l- まわりにきたらご挨拶
心得 o-d- ナナメにご用心
心得 o-d- 自分の用心
心得 o- 入れてください入れません
心得 o- 自分の弱い石から動くことを検討する
心得 o- キリチガイは場合によって対応を変える
心得 o-l- 離してきたら離して打つ
心得 o-l- むやみにツケない
ナナメにご用心 -- 自分の用心 : 自分のナナメを特に
離してきたら離して打つ <-d- むやみにツケない
まわりにきたらご挨拶 <-u- むやみにツケない


@enduml