@startuml
!include rule/rule.puml

package "対局中" {
  object 状況についた名前

  object コウ {
    お互いにアタリの状態が続くこと
  }

  object 大場 {
    大きく開けている場所に打てる状態
    布石段階で価値が大きい
  }

  object 急場 {
    すぐに対処しなければならない場所？
  }

  状況についた名前 <|-- コウ
  状況についた名前 <|-- 大場
  状況についた名前 <|-- 急場
  大場 <--> 急場

  コウ --> 1手前に戻す手は禁止

  object 盤上の位置についた名前

  object 星 {
    置き碁で最初に黒石を置く場所
    碁盤上に目印がついている
  }

  object 天元 {
    碁盤の中心点
  }

  盤上の位置についた名前 <|-- 星
  盤上の位置についた名前 <|-- 天元

  object 戦略

  !include in_playing_a_game/tactics.puml
  !include in_playing_a_game/guidlines.puml

  戦略 <--> 戦術 : 相互に影響する

  object 実利
}

' 練習方法
object 練習方法

object 詰め碁
object 棋譜並べ {
  既存の対局を棋譜に従って再現する
}
object NHK囲碁講座 {
  月ごとのテーマに沿った内容
}

練習方法 o-- 詰め碁 : 死活の練習
練習方法 o-- 棋譜並べ : 戦略の練習
練習方法 o-- NHK囲碁講座

' 関わる人について
object 棋士

object 小松英樹 {
  9段
  NHK囲碁講座の講師
}

object 井山裕太 {
  若手のすごい人
}

object 趙治勲 {
  俺でも名前知ってたすごい人
}

棋士 <|-- 小松英樹
棋士 <|-- 井山裕太
棋士 <|-- 趙治勲

'囲碁についてのあれこれ
!include trivia/idiom.puml

object ゲームの性質
note left : 数学や分類などでどう扱われているか

object アブストラクトゲーム {
  具体的なテーマがない抽象的なゲーム
  定石が研究されているものが多い
}

object 二人零和有限確定完全情報ゲーム {
  ゲーム理論による分類
  理論上は先読みが可能
  どちらかが最善手を打てば先手必勝か後手必勝か決まる
}

ゲームの性質 <|-- アブストラクトゲーム
ゲームの性質 <|-- 二人零和有限確定完全情報ゲーム

@enduml