@startuml
!include rule/rule.puml

' 対局に勝つための知識
object 状況についた名前

object コウ {
  お互いにアタリの状態が続くこと
}

object 大場 {
  大きく開けている場所に打てる状態
  布石段階で価値が大きい
}

object 急場 {
  すぐに対処しなければならない場所？
}

状況についた名前 <|-- コウ
状況についた名前 <|-- 大場
状況についた名前 <|-- 急場
大場 <--> 急場

コウ --> 1手前に戻す手は禁止

object 盤上の位置についた名前

object 星 {
  置き碁で最初に黒石を置く場所
  碁盤上に目印がついている
}

object 天元 {
  碁盤の中心点
}

盤上の位置についた名前 <|-- 星
盤上の位置についた名前 <|-- 天元

object 戦略
object 戦術 {
  1手をどう動かすか？
}

object 自分の石を起点に

戦術 <|-- 自分の石を起点に

object コスミ {
  斜めに打つ
  ただし、相手の石に隣接しない？
}

object ツケ {
  相手の石に隣接する様に石を置くこと？
}

object マガリ {
  曲がった形に打つ
}

自分の石を起点に <|-- コスミ
戦術 <|-- ツケ
自分の石を起点に <|-- マガリ

' 練習方法
object 練習方法

object 詰め碁
object 棋譜並べ {
  既存の対局を棋譜に従って再現する
}
object NHK囲碁講座 {
  月ごとのテーマに沿った内容
}

練習方法 o-- 詰め碁 : 死活の練習
練習方法 o-- 棋譜並べ : 戦略の練習
練習方法 o-- NHK囲碁講座

' 関わる人について
object 棋士

object 小松英樹 {
  9段
  NHK囲碁講座の講師
}

object 井山裕太 {
  若手のすごい人
}

object 趙治勲 {
  俺でも名前知ってたすごい人
}

棋士 <|-- 小松英樹
棋士 <|-- 井山裕太
棋士 <|-- 趙治勲

' まだ分類できないもの
object 心得 {
  東大教養囲碁講座から
}

object まわりにきたらご挨拶
object ナナメにご用心
object 入れてください入れません
object 自分の用心
object 自分の弱い石から動くことを検討する
object キリチガイは場合によって対応を変える
object 離してきたら離して打つ
object むやみにツケない

心得 o-l- まわりにきたらご挨拶
心得 o-r- 自分の用心
心得 o-- ナナメにご用心
心得 o-- 離してきたら離して打つ
心得 o-- むやみにツケない
心得 o-- 自分の弱い石から動くことを検討する
心得 o-u- キリチガイは場合によって対応を変える
心得 o-u- 入れてください入れません
自分の用心 <-d- ナナメにご用心 : 自分のナナメを特に
自分の用心 <-- 自分の弱い石から動くことを検討する
離してきたら離して打つ <-d- むやみにツケない
まわりにきたらご挨拶 <-u- むやみにツケない : ツケられた場合は対処する

'囲碁についてのあれこれ
object 慣用句としての用語
note left : 囲碁用語から慣用句的に使われる様になったもの

object 駄目 {
  打ってもどちらにも価値のない場所(目)
}

object 布石 {
  勢力圏を確保していこうという準備段階
}

慣用句としての用語 <|-- 駄目
慣用句としての用語 <|-- 布石

object ゲームの性質
note left : 数学や分類などでどう扱われているか

object アブストラクトゲーム {
  具体的なテーマがない抽象的なゲーム
  定石が研究されているものが多い
}

object 二人零和有限確定完全情報ゲーム {
  ゲーム理論による分類
  理論上は先読みが可能
  どちらかが最善手を打てば先手必勝か後手必勝か決まる
}

ゲームの性質 <|-- アブストラクトゲーム
ゲームの性質 <|-- 二人零和有限確定完全情報ゲーム

@enduml