@startuml

package "ルール全体" {
  object 基本ルール

  object ターン制 {
    交互に一手ずつ石を置く
    石は黒と白
    黒が先行する
  }
  object 置き碁 {
    所謂ハンデ戦
    盤面の星(黒い点)に
    黒石を置いた状態でスタート
    この場合は白が先行
  }
  object 終局 {
    ゲームの終了
    双方がパスしたら終わり
  }

  object 地 {
    自分の石で囲んだ陣地
  }
  object 着手禁止点 {
    石を置けない場所
    基本的には相手の地
    アタリになる場合は例外
  }
  object アタリ {
    後一手で相手の石をとれる状態
  }
  object 1手前に戻す手は禁止 {
    コウの状態で取られた石を1手後に取り返す
    延々と繰り返すことができてゲームが終わらなくなるので
  }

  基本ルール o-l- ターン制
  基本ルール o-u- 地
  基本ルール o-d- 着手禁止点
  基本ルール o-u- 1手前に戻す手は禁止
  基本ルール o- アタリ
  着手禁止点 <-- 地 : 基本
  着手禁止点 <-d- アタリ : 例外
  ターン制 <|-- 置き碁
  ターン制 <|-- 終局

  object 対局ごとに決められるルール

  object 持ち時間 {
    対局時に使用できる考慮時間
    大会や本戦、予選などによって異なる
  }

  object コミ {
    ゲームの性質上先手有利となるため
    後手に与えられる計算上のハンディキャップ
  }

  対局ごとに決められるルール o-- 持ち時間
  対局ごとに決められるルール o-- コミ
}

@enduml