@startuml

object 心得 {
  東大教養囲碁講座から
}

object まわりにきたらご挨拶
object ナナメにご用心
object 入れてください入れません
object 自分の用心
object 自分の弱い石から動くことを検討する
object キリチガイは場合によって対応を変える
object 離してきたら離して打つ
object むやみにツケない

心得 o-l- まわりにきたらご挨拶
心得 o-r- 自分の用心
心得 o-- ナナメにご用心
心得 o-- 離してきたら離して打つ
心得 o-- むやみにツケない
心得 o-- 自分の弱い石から動くことを検討する
心得 o-u- キリチガイは場合によって対応を変える
心得 o-u- 入れてください入れません
自分の用心 <-d- ナナメにご用心 : 自分のナナメを特に
自分の用心 <-- 自分の弱い石から動くことを検討する
離してきたら離して打つ <-d- むやみにツケない
まわりにきたらご挨拶 <-u- むやみにツケない : ツケられた場合は対処する

@enduml