@startuml

package "戦術" {
  object 起点
  note left : 周囲との位置関係を基準に1手をどう動かすか

  object 自分の石を起点に
  object 相手の石に対して

  起点 <|-- 自分の石を起点に
  起点 <|-- 相手の石に対して

  object コスミ {
    斜めに打つ
    ただし、相手の石に隣接しない？
  }

  object ツケ {
    相手の石に隣接する様に石を置くこと？
  }

  object マガリ {
    曲がった形に打つ
  }

  object トビ

  object ハサミ

  object ボウシ

  object 肩ツキ

  自分の石を起点に <|-- コスミ
  自分の石を起点に <|-- マガリ
  自分の石を起点に <|-- トビ
  相手の石に対して <|-- ツケ
  相手の石に対して <|-- ハサミ

  object シメツケ
}

@enduml